/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package za.co.absa.spline.producer.model

import java.util.UUID

case class ExecutionEvent (
  planId: UUID,
  labels: Option[Map[String, Seq[String]]],
  timestamp: Long,
  durationNs: Option[Long],
  discriminator: Option[String],
  error: Option[Any],
  extra: Option[Map[String, Any]]
)
