/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package za.co.absa.spline.producer.model

import java.util.UUID

case class ExecutionPlan (
  id: Option[UUID],
  name: Option[String],
  discriminator: Option[String],
  labels: Option[Map[String, Seq[String]]],
  operations: Operations,
  attributes: Option[Seq[Attribute]],
  expressions: Option[Expressions],
  systemInfo: NameAndVersion,
  agentInfo: Option[NameAndVersion],
  extraInfo: Option[Map[String, Any]]
)
