/**
 * OpenLineage
 * OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.absa.spline.harvester.dispatcher.openlineage.model.facet

import za.co.absa.spline.harvester.dispatcher.openlineage.model.openlineage.v2_0_2.DatasetFacet

case class ColumnLineageDatasetFacet(
  /* URI identifying the producer of this metadata. For example this could be a git url with a given tag or sha */
  _producer: String,
  /* The JSON Pointer (https://tools.ietf.org/html/rfc6901) URL to the corresponding version of the schema definition for this facet */
  _schemaURL: String,
  /* set to true to delete a facet */
  _deleted: Option[Boolean] = None,
  /* Column level lineage that maps output fields into input fields used to evaluate them. */
  fields: Map[String, ColumnLineage],
  /* Column level lineage that affects the whole dataset. This includes filtering, sorting, grouping (aggregates), joining, window functions, etc. */
  dataset: Option[Seq[InputField]] = None,
) extends DatasetFacet(_producer, _schemaURL, _deleted)
