/**
 * OpenLineage
 * OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.absa.spline.harvester.dispatcher.openlineage.model.facet

case class InputFieldTransformation(
  /* The type of the transformation. Allowed values are: DIRECT, INDIRECT */
  `type`: String,
  /* The subtype of the transformation */
  subtype: Option[String] = None,
  /* a string representation of the transformation applied */
  description: Option[String] = None,
  /* is transformation masking the data or not */
  masking: Option[Boolean] = None
)
