/**
 * OpenLineage
 * OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.absa.spline.harvester.dispatcher.openlineage.model.facet

  /**
   * Represents a single dependency on some field (column).
   */
case class InputField(
  /* The input dataset namespace */
  namespace: String,
  /* The input dataset name */
  name: String,
  /* The input field */
  field: String,
  transformations: Option[Seq[InputFieldTransformation]] = None
)
