/**
 * OpenLineage
 * OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package za.co.absa.spline.harvester.dispatcher.openlineage.model.openlineage.v2_0_2

import java.util.Date

/**
 * @param eventTime the time the event occurred at
 * @param producer URI identifying the producer of this metadata. For example this could be a git url with a given tag or sha for example: '''https://github.com/OpenLineage/OpenLineage/blob/v1-0-0/client'''
 * @param schemaURL The JSON Pointer (https://tools.ietf.org/html/rfc6901) URL to the corresponding version of the schema definition for this RunEvent for example: '''https://openlineage.io/spec/0-0-1/OpenLineage.json'''
 */
case class BaseEvent (
  eventTime: Date,
  producer: String,
  schemaURL: String
)
