/**
 * OpenLineage
 * OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package za.co.absa.spline.harvester.dispatcher.openlineage.model.openlineage.v2_0_2

/**
 * An input dataset
 *
 * @param namespace The namespace containing that dataset for example: '''my-datasource-namespace'''
 * @param name The unique name for that dataset within that namespace for example: '''instance.schema.table'''
 * @param facets The facets for this dataset
 * @param inputFacets The input facets for this dataset.
 */
case class InputDataset (
  namespace: String,
  name: String,
  facets: Option[Map[String, DatasetFacet]],
  inputFacets: Option[Map[String, InputDatasetFacet]]
)
