/**
 * OpenLineage
 * OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package za.co.absa.spline.harvester.dispatcher.openlineage.model.openlineage.v2_0_2

/**
 * @param namespace The namespace containing that job for example: '''my-scheduler-namespace'''
 * @param name The unique name for that job within that namespace for example: '''myjob.mytask'''
 * @param facets The job facets.
 */
case class Job (
  namespace: String,
  name: String,
  facets: Option[Map[String, JobFacet]]
)
