/**
 * OpenLineage
 * OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package za.co.absa.spline.harvester.dispatcher.openlineage.model.openlineage.v2_0_2

import java.util.UUID

/**
 * @param runId The globally unique ID of the run associated with the job.
 * @param facets The run facets.
 */
case class Run (
  runId: UUID,
  facets: Option[Map[String, RunFacet]]
)
